- name: Ensure config files are created
  hosts: east
  tasks:
    - name: Create a config file for each catalog host
      ansible.builtin.template:
        src: "catalog.conf.j2"
        dest: "/tmp/data{{ instance_number }}/catalog.conf"
        owner: vparham
        group: staff
        mode: "0644"

- name: Ensure catalog servers are started
  hosts: east
  tasks:
    - name: Start catalog server on each host
      ansible.builtin.shell: "nohup {{ yb_executable_dir }}/yb-master --flagfile=/tmp/data{{ instance_number }}/catalog.conf 2>&1  &"
