- name: Ensure config files are created
  hosts: east
  tasks:
    - name: Create a config file for each tserver host
      ansible.builtin.template:
        src: "tserver.conf.j2"
        dest: "/tmp/data{{ instance_number }}/tserver.conf"
        owner: vparham
        group: staff
        mode: "0644"

- name: Ensure tablet servers are started
  hosts: east
  tasks:
    - name: Start tablet server on each host
      ansible.builtin.shell: "nohup {{ yb_executable_dir }}/yb-tserver --flagfile=/tmp/data{{ instance_number }}/tserver.conf 2>&1  &"
