- name: Ensure data directories on the east side
  ansible.builtin.import_playbook: os/datadirs_east.yml

- name: Ensure the catalog servers on the east side
  ansible.builtin.import_playbook: yugabytedb/catalog_east.yml

- name: Ensure the tservers on the east side
  ansible.builtin.import_playbook: yugabytedb/tservers_east.yml

- name: Ensure the placement policy
  ansible.builtin.import_playbook: os/placement_east.yml

- name: Ensure the sql table for the fuzzy matching demo
  ansible.builtin.import_playbook: ddl/sql/stretch/moma.yml

- name: Ensure the cql table for the fuzzy matching demo
  ansible.builtin.import_playbook: ddl/cql/stretch/moma.yml

- name: Ensure data set is available
  ansible.builtin.import_playbook: dml/datasets/moma.yml

- name: Ensure sql data for the fuzzy matching demo
  ansible.builtin.import_playbook: dml/sql/moma.yml

- name: Ensure cql data for the fuzzy matching demo
  ansible.builtin.import_playbook: dml/cql/moma.yml
