- name: Ensure the US Department of Education College Scorecard data set is present
  hosts: east-node1
  tasks:
    - name: Download Institution data
      ansible.builtin.get_url:
        url: https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-Institution_09262023.zip
        dest: /tmp/Most-Recent-Cohorts-Institution_09262023.zip
        mode: "0775"
        validate_certs: false
    - name: Download Fields of Study data
      ansible.builtin.get_url:
        url: https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-Field-of-Study_09262023.zip
        dest: /tmp/Most-Recent-Cohorts-Field-of-Study_09262023.zip
        mode: "0775"
        validate_certs: false

- name: Unarchive the files
  hosts: east-node1
  tasks:
    - name: Unzip Institution data file
      ansible.builtin.unarchive:
        src: /tmp/Most-Recent-Cohorts-Institution_09262023.zip
        dest: /tmp/
        remote_src: yes
    - name: Unzip Institution data file
      ansible.builtin.unarchive:
        src: /tmp/Most-Recent-Cohorts-Field-of-Study_09262023.zip
        dest: /tmp/
        remote_src: yes

- name: Install Python packages
  hosts: east-node1
  tasks:
    - name: Install pandas
      ansible.builtin.pip:
        name: pandas

- name: Clean the data
  hosts: east-node1
  tasks:
    - name: Clean it
      ansible.builtin.command: "python3 {{ playbook_dir }}/clean-ipeds.py"

- name: Load the data
  hosts: east-node1
  tasks:
    - name: Load cleaned data into ipeds table
      ansible.builtin.command: >
        {{ yb_executable_dir }}/ysqlsh -h {{ ansible_host }} college_scorecard_sql -c "copy ipeds from '/tmp/Most-Recent-Cohorts-Institution-cleaned.csv' with (format csv, DELIMITER ',', HEADER)"
