- name: Ensure data dirs
  hosts: east
  tasks:
    - name: Create a directory for each host
      ansible.builtin.file:
        path: "/tmp/data{{ instance_number }}"
        state: directory
        owner: "vparham"
        group: "staff"
        mode: "0750"
