- name: Ensure placement info on west nodes
  hosts: west-node1
  tasks:
    - name: Set up placement info
      ansible.builtin.command: "{{ yb_executable_dir }}/yb-admin --master_addresses {{ yb_catalog }} modify_placement_info {{ yb_placement_info }} {{ yb_replication }}"
